name: Create Branch
on:
  issues: 
    types: [ opened ] 
  issue_comment:
    types: [ created ]
    
jobs:
  create-branch:
    name: Create Branch
    runs-on: ubuntu-latest
    steps:
    - name: Create Issue Branch
      id: Create_Issue_Branch
      uses: robvanderleek/create-issue-branch@v1.5
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Echo branch name
      run: echo ${{ steps.Create_Issue_Branch.outputs.branchName }}
